# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الرسامة')),
                ('can_manage_confessions', models.BooleanField(default=True, verbose_name='إدارة الاعتراف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'ملف الكاهن',
                'verbose_name_plural': 'ملفات الكهنة',
            },
        ),
        migrations.CreateModel(
            name='ServantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_prayer_data', models.BooleanField(default=False, verbose_name='عرض بيانات الصلاة')),
                ('can_view_mass_data', models.BooleanField(default=False, verbose_name='عرض بيانات القداس')),
                ('joined_service_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الخدمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'ملف الخادم',
                'verbose_name_plural': 'ملفات الخدام',
            },
        ),
        migrations.CreateModel(
            name='ServiceLeaderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_confession_status', models.BooleanField(default=False, verbose_name='عرض حالة الاعتراف')),
                ('appointed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'ملف مسؤول الخدمة',
                'verbose_name_plural': 'ملفات مسؤولي الخدمة',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('role', models.CharField(choices=[('priest', 'كاهن'), ('service_leader', 'مسؤول خدمة'), ('servant', 'خادم'), ('member', 'مخدوم')], default='member', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='طاقم الإدارة')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='FCM Token')),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, null=True)),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='الإشعارات مفعلة')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم ولي الأمر')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='هاتف ولي الأمر')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المعمودية')),
                ('is_active_member', models.BooleanField(default=True, verbose_name='عضو نشط')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('assigned_servant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL, verbose_name='الخادم المسؤول')),
            ],
            options={
                'verbose_name': 'ملف المخدوم',
                'verbose_name_plural': 'ملفات المخدومين',
                'ordering': ['user__first_name'],
            },
        ),
    ]
