# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='church.servicegroup', verbose_name='مجموعة الخدمة'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priestprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priest_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servantprofile',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.servicegroup', verbose_name='مجموعة الخدمة'),
        ),
        migrations.AddField(
            model_name='servantprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_servants', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AddField(
            model_name='servantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceleaderprofile',
            name='service_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.servicestage', verbose_name='مرحلة الخدمة'),
        ),
        migrations.AddField(
            model_name='serviceleaderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviceleaderprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
