# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('phone_call', 'مكالمة هاتفية'), ('visit', 'زيارة'), ('chat_message', 'رسالة'), ('meeting', 'اجتماع'), ('other', 'أخرى')], max_length=20, verbose_name='النوع')),
                ('date', models.DateTimeField(verbose_name='التاريخ والوقت')),
                ('summary', models.TextField(verbose_name='ملخص')),
                ('outcome', models.TextField(blank=True, null=True, verbose_name='النتيجة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('completed', 'مكتملة'), ('pending', 'معلقة'), ('overdue', 'متأخرة'), ('cancelled', 'ملغاة')], default='pending', max_length=15, verbose_name='الحالة')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='تاريخ المتابعة القادمة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_records', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups_made', to=settings.AUTH_USER_MODEL, verbose_name='الخادم')),
            ],
            options={
                'verbose_name': 'سجل متابعة',
                'verbose_name_plural': 'سجلات المتابعة',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['member', 'status'], name='followups_f_member__8233d7_idx'), models.Index(fields=['servant', 'status'], name='followups_f_servant_d470b1_idx'), models.Index(fields=['next_followup_date'], name='followups_f_next_fo_2fd24d_idx')],
            },
        ),
    ]
