# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('notification_type', models.CharField(choices=[('prayer_alert', 'تنبيه صلاة'), ('prayer_followup', 'متابعة صلاة'), ('attendance_reminder', 'تذكير حضور'), ('birthday', 'عيد ميلاد'), ('followup_due', 'متابعة مطلوبة'), ('message', 'رسالة'), ('announcement', 'إعلان'), ('confession_overdue', 'تأخر اعتراف'), ('absence_alert', 'تنبيه غياب'), ('system', 'نظام')], max_length=25, verbose_name='النوع')),
                ('reference_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المرجع')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='معرف المرجع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('is_pushed', models.BooleanField(default=False, verbose_name='تم الإرسال')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='مجدول لـ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx')],
            },
        ),
    ]
