# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_confessed', models.BooleanField(default=False, verbose_name='اعترف')),
                ('last_confession_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر اعتراف')),
                ('follow_up_note', models.TextField(blank=True, help_text='ملاحظة إدارية فقط - لا تخزّن محتوى الاعتراف أبداً', null=True, verbose_name='ملاحظة المتابعة')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='متأخر')),
                ('overdue_threshold_days', models.IntegerField(default=30, verbose_name='حد التأخر (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confession_records', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_confessions', to=settings.AUTH_USER_MODEL, verbose_name='سُجل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل اعتراف',
                'verbose_name_plural': 'سجلات الاعتراف',
                'ordering': ['-updated_at'],
            },
        ),
    ]
