# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصلاة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('scheduled_time', models.TimeField(verbose_name='وقت الصلاة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'صلاة',
                'verbose_name_plural': 'الصلوات',
                'ordering': ['order', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PrayerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('completed', 'تمت'), ('missed', 'فائتة'), ('snoozed', 'مؤجلة'), ('pending_confirmation', 'في انتظار التأكيد')], default='pending', max_length=25, verbose_name='الحالة')),
                ('scheduled_time', models.DateTimeField(verbose_name='الوقت المجدول')),
                ('alert_shown_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت عرض التنبيه')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستجابة الأولى')),
                ('followup_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال المتابعة')),
                ('final_response_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستجابة النهائية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_logs', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prayers.prayerdefinition', verbose_name='الصلاة')),
            ],
            options={
                'verbose_name': 'سجل صلاة',
                'verbose_name_plural': 'سجلات الصلوات',
                'indexes': [models.Index(fields=['member', 'date'], name='prayers_pra_member__4f90c9_idx'), models.Index(fields=['date', 'status'], name='prayers_pra_date_13c0af_idx')],
                'unique_together': {('member', 'prayer', 'date')},
            },
        ),
    ]
