# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('attended', models.BooleanField(default=False, verbose_name='حضر')),
                ('church_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الكنيسة')),
                ('mass_type', models.CharField(blank=True, help_text='مثال: قداس أحد، قداس عيد', max_length=100, null=True, verbose_name='نوع القداس')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_mass_records', to=settings.AUTH_USER_MODEL, verbose_name='سُجل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل حضور القداس',
                'verbose_name_plural': 'سجلات حضور القداس',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['member', 'date'], name='mass_attend_member__8c9f7c_idx')],
            },
        ),
    ]
