# Generated by Django 6.0.3 on 2026-04-04 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FridayMeetingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='تاريخ الجمعة')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_locked', models.BooleanField(default=False, verbose_name='مغلق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('service_stage', models.ForeignKey(blank=True, help_text='اتركه فارغاً لجميع المراحل', null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.servicestage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'جلسة اجتماع الجمعة',
                'verbose_name_plural': 'جلسات اجتماع الجمعة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FridayAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'معتذر'), ('late', 'متأخر')], default='absent', max_length=10, verbose_name='الحالة')),
                ('absence_reason', models.TextField(blank=True, null=True, verbose_name='سبب الغياب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_friday_records', to=settings.AUTH_USER_MODEL, verbose_name='سُجل بواسطة')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='المخدوم')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='friday_attendance.fridaymeetingsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'سجل حضور الجمعة',
                'verbose_name_plural': 'سجلات حضور الجمعة',
                'indexes': [models.Index(fields=['member', 'status'], name='friday_atte_member__e16ca6_idx'), models.Index(fields=['session', 'status'], name='friday_atte_session_0fb70e_idx')],
                'unique_together': {('session', 'member')},
            },
        ),
    ]
